export const heroImg = "/heroimg.png"
export const starImg = "/star.png"
export const tShirtImg = "/tshirt.png"
export const browseImg1 = "/browse-img1.png"
export const browseImg2 = "/browse-img2.png"
export const browseImg3 = "/browse-img3.png"
export const browseImg4 = "/browse-img4.png"
export const greenTick = "/greentick.png"